name: heuristic
on: workflow_dispatch
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.11'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt install -y python-is-python3
          pip install tomli_w==1.2.0
      - run: |
          python -m pip install --upgrade hatch
      - run: |
          hatch run +py=3.11 test:with-coverage
      - run: |
          hatch run +py=3.11 integration:test
    env:
      ACCEPT_EULA: Y
      BOOLVAR: 'false'
      BOOTSTRAP_HASKELL_NONINTERACTIVE: '1'
      COVERAGE_RUN: 'true'
      DEBIAN_FRONTEND: noninteractive
      DOTNET_MULTILEVEL_LOOKUP: '0'
      DOTNET_NOLOGO: '1'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: '1'
      HATCH_ENV_ACTIVE: test.py3.11-min-req
      HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS: '3650'
      HOMEBREW_NO_AUTO_UPDATE: '1'
      HOSTNAME: pop-os
      ImageOS: ubuntu22
      ImageVersion: 20250622.1.0
      LC_CTYPE: C.UTF-8
      POWERSHELL_DISTRIBUTION_CHANNEL: GitHub-Actions-ubuntu22
      SHLVL: '1'
      # SOURCE_DATE_EPOCH: '0'
      TERM: xterm
      VARNAME: Hello, World!
      _PYI_LINUX_PROCESS_NAME: sawra
      _PYI_PARENT_PROCESS_LEVEL: '1'
